### ISSUE TITLE
`brew install rbenv/tap/openssl@1.0` not working anymore

### ISSUE THREAD

**Issue by MathieuDerelle** [rbenv/homebrew-tap#1]
```
➜  ~ brew install rbenv/tap/openssl@1.0
Error: No available formula or cask with the name "rbenv/tap/openssl@1.0".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
```

**Comment by eddroid** [comment]
```sh
brew tap rbenv/tap
brew install rbenv/tap/openssl@1.0
```

**Comment by namratasaun** [comment]
![image](https://user-images.githubusercontent.com/35791871/128296711-f4b9bf7d-163a-4465-986a-8100b7cf551a.png)
getting this error. any idea @MathieuDerelle @eddroid

**Comment by eddroid** [comment]
Are you on the new Apple Silicon M1 device? Try https://github.com/rbenv/homebrew-tap/issues/4 ➡️ https://github.com/rbenv/homebrew-tap/pull/2

**Comment by harry-at-cogwrite** [comment]
Stuck - mysql workbench needs openssl 1.0 which I cannot seem to install on Monterey 12.3 
i tried:
<img width="1184" alt="1-command_error_mysql_workbench_needs_openssl_1 0_220318_version_8 0 21" src="https://user-images.githubusercontent.com/42248938/159124074-28e718c5-8800-4e02-a9e1-c2b8db19ace2.png">

then:
<img width="1184" alt="2_openssl_1 0_cannot_install_220318_version_8 0 21" src="https://user-images.githubusercontent.com/42248938/159124094-9c7610f1-9b74-47fd-b7b6-1590420034e9.png">

**Comment by eddroid** [comment]
@harry-at-cogwrite It might be this line:

```
Cannot create directory /usr/local/etc/openssl/certs: Permission denied
```

If you're on a Mac with multiple user accounts, typically only one owns the `/usr/local` directory. How to fix that given your context is a Unix-style permissions issue. Do you have only one dev user account (un: `harry`) or do you want multiple to be able to install packages? Are you a "`sudo` all the things" person? Are you comfortable with the `chown` and `chmod` shell commands?

Have you tried asking the [mysqlworkbench folks](https://github.com/Homebrew/homebrew-cask/issues?q=is%3Aissue+MySQLworkbench+is%3Aclosed)? (e.g. [Permission denied error](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/error_examples.md#permission-denied-error))

It looks like you're trying to do a `mysqldump` from a remote host. Have you tried `ssh`ing into the host to dump the data from there instead?

**Comment by harry-at-cogwrite** [comment]
Thank you Eddroid!  That was exactly the problem.   I have multiple user accounts and so found at /usr/local/opt/openssl  i had multiple entries and changed them chown'd them all to me. which was like this:
``` 
lrwxr-xr-x  1 harry  admin    28B Jan 28 12:57 openssl@1.1 -> ../Cellar/openssl@1.1/1.1.1m
lrwxr-xr-x  1 harry  admin    25B Mar 19 06:10 openssl@3 -> ../Cellar/openssl@3/3.0.2
lrwxr-xr-x  1 harry  admin    25B Mar 19 06:10 openssl -> ../Cellar/openssl@3/3.0.2
lrwxr-xr-x  1 harry  admin    28B Mar 19 07:25 openssl@1.0 -> ../Cellar/openssl@1.0/1.0.2t
```
so i then had to do this:

ln -sfn /usr/local/Cellar/openssl@1.0/1.0.2t /usr/local/opt/openssl to have 

/usr/local/opt/openssl/lib/libssl.1.0.0.dylib visible as such;  the mysqldump command then worked fine, and after testing some things, I then issued this command 

ln -sfn /usr/local/Cellar/openssl@3/3.0.2 /usr/local/opt/openssl

to put the apple approved openssl 3 back in place.

turns out there are some bugs seen with certain unicode sequences that still prevented me from dumping a remote mysql database to local and the posting it my mysql or mysql workbech, so i had to roll back to mysql 2.0.13 to be able to upload the backup (utf8 encoding) to install locally. 

thanks for pointing that out.  i eventually did see it. I also see many issues out there with legacy code that still looks for that libssl.1.0.0.dynlib, so at least next time I will know what to do!

thanks so much!!

harry

**Comment by eddroid** [comment]
There are usually compile args like `--openssldir` or `--with-openssl-dir` and env vars like `OPENSSL_CONFIG` you can use to override OpenSSL paths without doing the `ln` dance, but whatever works is good.

**Comment by t1-tracey** [comment]
I have the issue on #4 with a m1 MacBook 2020, but #2 does not work as:

> This updates the formula from OpenSSL 1.0.2t to the latest 1.0.2u.
>
> It also adds a small patch to add a build target darwin64-arm64-cc for the new Apple Silicon M1 ARM based Macs.

`mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')`

```
Reason: tried: '/usr/local/opt/openssl/lib/libssl.1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/libssl.1.0.0.dylib' (no such file), '/usr/lib/libssl.1.0.0.dylib' (no such file), '/opt/homebrew/Cellar/openssl@1.0/1.0.2u/lib/libssl.1.0.0.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Comment by eddroid** [comment]
@t1-tracey That looks like an M1 MacBook problem. The fact that you have an `arm64` version of `libssl` hints that you may already have OpenSSL installed for M1, but you're trying to install something else on top that isn't Apple Silicon compatible yet. That comment belongs in https://github.com/rbenv/homebrew-tap/pull/2 or possibly a separate issue if there is some other thing you're installing that's trying to pull in OpenSSL for `x86`.

**Comment by t1-tracey** [comment]
Yeah sorry to clarify — it seems like #2 was not the answer for me, in response to [this post](https://github.com/rbenv/homebrew-tap/issues/1#issuecomment-893601215):

> Are you on the new Apple Silicon M1 device? Try https://github.com/rbenv/homebrew-tap/issues/4 ➡️ https://github.com/rbenv/homebrew-tap/pull/2

I got issue solved by just changing to ruby 3.0.2 rather than using 2.6.x, but this part is probably not relevant anymore here

**Comment by RafaBlockDev** [comment]
It worked for me this:
`curl https://raw.githubusercontent.com/rbenv/homebrew-tap/e472b7861b49cc082d1db0f66f265368da107589/Formula/openssl%401.0.rb -o openssl@1.0.rb

brew install ./openssl@1.0.rb

rm -rf ./openssl@1.0.rb`

Go a head and build your project!

![champion-trophy](https://user-images.githubusercontent.com/86583080/168413118-e9adf2de-e224-44f7-a4c3-460e2ff81a27.png)

**Comment by smaboshe** [comment]
Thanks, @RafaBlockDev. I tried [this](https://github.com/rbenv/homebrew-tap/issues/1#issuecomment-1126650335) and get an error even with `makedepend` installed:

```
make
depend

making depend in crypto...
../util/domd: line 23: makedepend: command not found
mv: Makefile.new: No such file or directory
make[1]: *** [local_depend] Error 127
make: *** [depend] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!
```

Any thoughts on what might be happening?

**Comment by RafaBlockDev** [comment]
Did you copy and paste right this one command? 

Try again now with this order mate @smaboshe 🤔

`curl https://raw.githubusercontent.com/rbenv/homebrew-tap/e472b7861b49cc082d1db0f66f265368da107589/Formula/openssl%401.0.rb -o [openssl@1.0.rb](mailto:openssl@1.0.rb) brew install ./openssl@1.0.rb rm -rf ./openssl@1.0.rb`

**Comment by smaboshe** [comment]
Thanks!

I did a copy and paste again and still get the same issue ... 🤔

**Comment by RafaBlockDev** [comment]
Hey man! I found something could help you! 👋🏻

There are icc targets in 1.0.2[!]. And quite elaborate in sense that the even eliminate dependencies on icc run-times components, so that you can move build to computer without icc installed. Anyway, the problem was addressed in https://github.com/openssl/openssl/pull/6261. 🚀

![bookmark](https://user-images.githubusercontent.com/86583080/168928828-42939550-cfa8-4048-a03a-c2104af5eab0.png)

**Comment by Alireza17224** [comment]
Same issue here

**Comment by mislav** [comment]
Should be fixed by https://github.com/rbenv/homebrew-tap/commit/4af536aae6f5c7c10f156008b6db2353cdfcc5e7

**Comment by jlugner** [comment]
Still having this issue on M1. Getting the make error @smaboshe was having:

```
% brew install rbenv/tap/openssl@1.0
==> Downloading https://formulae.brew.sh/api/cask.jws.json
############################################################################################################################################################################################################################################## 100.0%
==> Fetching rbenv/tap/openssl@1.0
==> Downloading https://www.openssl.org/source/openssl-1.0.2u.tar.gz
############################################################################################################################################################################################################################################## 100.0%
==> Installing openssl@1.0 from rbenv/tap
==> Downloading https://formulae.brew.sh/api/formula.jws.json
############################################################################################################################################################################################################################################## 100.0%
==> Patching
==> perl ./Configure --prefix=/opt/homebrew/Cellar/openssl@1.0/1.0.2u --openssldir=/opt/homebrew/etc/openssl no-ssl2 no-ssl3 no-zlib shared enable-cms darwin64-arm64-cc enable-ec_nistp_64_gcc_128
==> make depend
Last 15 lines from /Users/me/Library/Logs/Homebrew/openssl@1.0/02.make:
2023-12-14 18:35:58 +0000

make
depend

making depend in crypto...
../util/domd: line 23: makedepend: command not found
mv: Makefile.new: No such file or directory
make[1]: *** [local_depend] Error 127
make: *** [depend] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/rbenv/homebrew-tap/issues
```

Not sure if it makes a difference, but I do have makedepend available on my system:
```
% which makedepend
/opt/homebrew/bin/makedepend
```

**Comment by mislav** [comment]
> Not sure if it makes a difference, but I do have makedepend available on my system:

I do not have makedepend and I cannot reproduce the failure on M1. Maybe temporarily unlinking it from Homebrew would help `openssl@1.0` compilation succeed?

**Comment by jlugner** [comment]
> > Not sure if it makes a difference, but I do have makedepend available on my system:
> 
> I do not have makedepend and I cannot reproduce the failure on M1. Maybe temporarily unlinking it from Homebrew would help `openssl@1.0` compilation succeed?

Thanks for replying.

Seems to make no difference:

```
➜  ruby_project git:(master) ✗ brew unlink makedepend
Unlinking /opt/homebrew/Cellar/makedepend/1.0.8... 2 symlinks removed.
➜  ruby_project git:(master) ✗ brew install rbenv/tap/openssl@1.0
Running `brew update --auto-update`... ==> Auto-updated Homebrew!
Updated 3 taps (homebrew/cask-versions, homebrew/services and homebrew/core). ==> New Formulae
opensca-cli

You have 4 outdated formulae installed. ==> Fetching rbenv/tap/openssl@1.0 ==> Downloading https://www.openssl.org/source/openssl-1.0.2u.tar.gz
Already downloaded: /Users/me/Library/Caches/Homebrew/downloads/cb69ca61319d7186eb55397eb90cec0c2f56d8722af71a851bb35194ecaf3359--openssl-1.0.2u.tar.gz ==> Installing openssl@1.0 from rbenv/tap ==> Patching
==> perl ./Configure --prefix=/opt/homebrew/Cellar/openssl@1.0/1.0.2u --openssldir=/opt/homebrew/etc/openssl no-ssl2 no-ss ==> make depend
Last 15 lines from /Users/me/Library/Logs/Homebrew/openssl@1.0/02.make:
2023-12-16 08:00:28 +0000

make
depend

making depend in crypto...
../util/domd: line 23: makedepend: command not found
mv: Makefile.new: No such file or directory
make[1]: *** [local_depend] Error 127
make: *** [depend] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/rbenv/homebrew-tap/issues
 ```

**Comment by mislav** [comment]
Thanks for checking. Feel free to open a new issue for this problem. I do not know how to go about investigating this, however, since I can't reproduce nor do I understand the logic of the build script that corresponds to the error trace.

**Comment by jlugner** [comment]
> Thanks for checking. Feel free to open a new issue for this problem. I do not know how to go about investigating this, however, since I can't reproduce nor do I understand the logic of the build script that corresponds to the error trace.

Thanks, will do. Don't really know how to proceed myself.

**Comment by hellysmile** [comment]
Hey, I had same issue and prepared a patched version brew Formula

https://gist.github.com/hellysmile/f58a6e32656ac1101cf6a64d0674f2c8 with openssl 1.0.2 patch from https://github.com/lavabit/magma
